version: '3'
services: 
    db:
        image: postgres
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password

    bot:
        build: .
        volumes: 
            - .:/code
        depends_on: 
            - db
        environment: 
            - DISCORD_TOKEN=<Discord api token>
            # postgresql://user:password@db/db_name
            - POOL_CONFIG=postgresql://postgres:postgres@db/postgres
            - POSTGRES_PASSWORD=password
            # OPTIONAL used for mimic command
            - MERRIAM_TOKEN=<Merriam webster thesaurus api token>
        command: ["./wait-for-postgres.sh", "db", "pipenv", "run", "python", "fellow_kids.py"]